version: '3.8'
services:
  postgres-iam:
    image: postgres:15-alpine
    container_name: uniride_iam_db
    environment:
      POSTGRES_USER: campusdrive_user
      POSTGRES_PASSWORD: campusdrive_password
      POSTGRES_DB: iam_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_iam_data:/var/lib/postgresql/data

volumes:
  postgres_iam_data:
